{{- if .Values.cviewdata.ingress.enabled -}}
{{- $fullName := print (include "nwperf.fullname" .) "-cviewdata" -}}
{{- $ingressPath := .Values.cviewdata.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "nwperf.name" . }}-cviewdata
    chart: {{ template "nwperf.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.cviewdata.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.cviewdata.ingress.tls }}
  tls:
  {{- range .Values.cviewdata.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.cviewdata.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
  {{- end }}
{{- end }}
