apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "nwperf.fullname" . }}-web
  labels:
    app: {{ template "nwperf.name" . }}-web
    chart: {{ template "nwperf.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    kubernetes.io/ingress.class: pnnl
spec:
  rules:
  - host: {{ .Values.web.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "nwperf.fullname" . }}-web
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.web.hostname }}
    secretName: {{ .Values.web.sslSecretName }}
