enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"QueryBuilder.js",
	"UserManager.js",
	"JobManager.js",
	"JobTable.js",
	"JobView.css",
	"jquery.js",
	"jquery.flot.js",
	"jquery.flot.crosshair.js",
	"jquery.flot.selection.js",
	"jquery.flot.resize.js",
	"jquery.flot.time.js",
	"Flot.js",
	"JobView.js",
	"App.css",
	"App.js"
);
