enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"QueryBuilder.js",
	"UserManager.js",
	"JobManager.js",
	"JobTable.js",
	"JobView.css",
	"jquery.js",
	"jquery.flot.js",
	"jquery.crosshair.js",
	"jquery.selection.js",
	"JobView.js",
	"App.css",
	"App.js"
);
